name: "reusable: the workflow it self"

on:
  workflow_call:
    inputs:
      some_path:
        required: true
        type: string
    secrets:
      my_secret:
        required: true

jobs:
  test:
    name: 'Job custom name'
    runs-on: ubuntu-latest

    steps:
      - name: 'printenv'
        run: printenv

      - name: 'print variable "some-path"'
        run: echo "'${{ vars.SOME_PATH }}'"

      - name: 'print input "some-path"'
        run: echo "'${{ inputs.some_path }}'"

      - name: 'print undefined variable'
        run: echo "'${{ vars.UNDEFINED }}'"

      - name: 'print secret'
        run: echo "'${{ secrets.my_secret }}'"
