name: "reusable-stag: Use reusable workflow"

on:
  # Triggers the workflow on tag called 'reusable-stag*'
  push:
    tags:
      - reusable-stag*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call:
    name: 'Run custom reusable workflow'
    uses: ./.github/workflows/reusable.yml
    with:
      some_path: '/usr/local/etc/shadow'
      stage: 'staging'
    secrets:
      my_secret: 'hello'
