name: "reusable-stag: Use reusable workflow"

on:
  # Triggers the workflow on tag called 'reusable-stag*'
  push:
    tags:
      - reusable-stag*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable.yml
    with:
      some-path: '/usr/local/etc/shadow'
      secrets: inherit
